parse.py: port to pandas 2.
nextstrain/augur pull request #1436
Opened 2024-03-10 08:56 UTC by emollier

Replace parse_time_string() by parse_datetime_string_with_reso() to gain pandas 2.0 compatitibility.

This change was hinted by s3v in [Debian bug #1044079] and allows the resolution of the github issue #1303 appropriately.

[Debian bug #1044079]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1044079#46

Thanks: s3v <c0llapsed@yahoo.it>

PS: filling the mandatory form below for your convenience.

## Description of proposed changes

This change modifies augur/parse.py by replacing parse_time_string() by parse_datetime_string_with_reso() in order to gain pandas 2.0 compatitibility.

## Related issue(s)

#1303 

## Checklist

- [x] Checks pass with the newer pandas 2 versions, but I have not tested how things behaved with the older pandas 1.x, so there are good chances some further adjustments will be necessary if you want to support both. 
- [ ] If making user-facing changes, add a message in [CHANGES.md](https://github.com/nextstrain/augur/blob/HEAD/CHANGES.md) summarizing the changes in this PR

2024-03-11 18:04 UTC, victorlin requested changes
@emollier thanks for the PR. We have no current plans to support pandas version 2 and will continue to pin to 1.x for PyPI/Bioconda until we're ready to support 2.x in all other parts of the codebase.

In the meantime, this specific call can be made compatible with both versions for environments that allow more flexible dependency versions.

2024-03-11 18:04 UTC, victorlin commented on augur/parse.py
> +        results = parsing.parse_datetime_string_with_reso(d, dayfirst=dayfirst)
Noting that the long-term solution here is to replace this call with a public API call as mentioned in https://github.com/nextstrain/augur/pull/601#pullrequestreview-465439460.

2024-03-11 19:20 UTC, emollier commented
Thank you for your time and your review, I took some time to test it in various conditions to make sure it works as expected, and saw no issues indeed.  Even if you keep the pin to pandas 1.x, this may facilitate the change to pandas 2.x series when you feel that you are ready for it.

> Noting that the long-term solution here is to replace this call with a public API call as mentioned in #601 (review).

I very much agree about an implementation using the public API: this would avoid further risks of abrupt breakage without notice or guidance from pandas.  I'm afraid however that I'm not comfortable enough with augur's field of application nor pandas itself to be able to propos such a change myself.  :/

2024-03-11 19:30 UTC, victorlin commented
@emollier thanks for the update! I've just approved the test runs. Once they pass, I'll add a changelog entry and get this merged.

2024-03-11 19:36 UTC, emollier commented
You're welcome,
Have a nice day,  :)
Étienne.

2024-03-11 20:37 UTC, merged

2024-07-13 09:52 UTC, victorlin commented
This does not work with pandas versions >=2.2.0 due to removal of `pandas.core.tools.datetimes.parsing` in https://github.com/pandas-dev/pandas/commit/625d8d6e53b11f8099eb8987e030e28cdb972747