merge: Add `--sequences` + `--output-sequences`
nextstrain/augur pull request #1601
Opened 2024-08-27 17:48 UTC by victorlin

## Description of proposed changes

Initial prototype for sequence support in `augur merge`.

## Related issue(s)

Closes #1579

## Checklist

- [ ] Address FIXMEs
- [ ] Automated checks pass
- [ ] [Check][1] if you need to add a changelog message
- [ ] [Check][2] if you need to add tests
- [ ] [Check][3] if you need to update docs

[1]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#updating-the-changelog
[2]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#testing
[3]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#when-to-update

2024-10-23 21:50 UTC, victorlin commented
@tsibley this is ready for initial review whenever you get the chance!

2024-10-24 22:32 UTC, genehack reviewed
Kinda skimmed, so not marking approved at this point. 

Would be nice if methods had return type annotations too; seemed like they generally didn't.

2024-10-24 22:32 UTC, genehack commented on augur/merge.py
> +    # These will make more sense when sequence support is added.
comment can go away, as this _is_ adding sequence support?

2024-10-24 22:32 UTC, genehack commented on augur/merge.py
> +    ):
```suggestion
def load_metadata(
        db: Database,
        metadata: List[NamedMetadata],
    ) -> List[NamedMetadata]:
```

2024-10-24 22:32 UTC, genehack commented on augur/merge.py
> +        raise AugurError("'seqkit' is not installed! This is required to merge sequences.")
This duplicates a check that's also done on L717; that latter check is also looking at the `SEQKIT` env var, which this check isn't. 

I'm not sure which one is correct, but it doesn't seem like both are useful?

2024-12-16 19:45 UTC, jameshadfield commented on tests/functional/merge/cram/merge-sequences.t
> +BASIC USAGE
🐛 at 81b22d79. when a FASTA doesn't have a trailing new line it results in a malformed merged FASTA.

e.g. 2 fasta files each without trailing new lines:
```
# A.fasta
>A
ATGC
# B.fasta
>B
ATGC
```

```console
$ augur merge  --sequences A=A.fasta B=B.fasta  --output-sequences -
>B
ATGC>AATGC
```

I also find it strange that B comes before A in the output - is this on purpose?

2025-01-07 00:35 UTC, victorlin commented on augur/merge.py
> +    ):
Removed the return statement instead since the value is not being used: 0e6f453dc61d374b85d38560e66de8246aeb9db2

2025-01-07 00:35 UTC, victorlin commented on augur/merge.py
> +    # These will make more sense when sequence support is added.
Done: befe5f85275a85f78654860e20a4375f278192c8

2025-01-07 00:35 UTC, victorlin commented on augur/merge.py
> +        raise AugurError("'seqkit' is not installed! This is required to merge sequences.")
Removed the first one and kept the latter: 6ce8d2c0fb6f3d6358e2056ea337c84e826b74a1

2025-01-07 00:35 UTC, victorlin commented on tests/functional/merge/cram/merge-sequences.t
> +BASIC USAGE
Good catch on the newline bug. Safe to say we should support FASTAs without trailing new line?

Ideally, the missing newline is added in the subprocess, but that means another external dependency (see answers to a [similar StackOverflow question](https://unix.stackexchange.com/q/345548)). There should be a way to do it in Python, but that would require loading the contents into memory or seeking to the end of the file to check the last byte, which means full decompression ([at least for gzip](https://stackoverflow.com/a/25985724)).

2025-01-07 00:35 UTC, victorlin commented on tests/functional/merge/cram/merge-sequences.t
> +BASIC USAGE
> I also find it strange that B comes before A in the output - is this on purpose?

Yes, this is because `seqkit rmdup` deduplicates in reverse of `augur merge`'s desired order. I think the only way to retain original order is to replace `seqkit rmdup` with another tool (I don't know of any) or our own function that deduplicates (likely to be much slower than `seqkit rmdup` for large files if it's Python-based). Do you think it's important to retain the original order?

2025-01-07 00:51 UTC, jameshadfield commented on tests/functional/merge/cram/merge-sequences.t
> +BASIC USAGE
> I guess it needs a resolved segment only to support the config form of:

Probably not, I just found it surprising and wanted to note it here. 

> Ideally, the missing newline is added in the subprocess

Right. `seqkit rmdup` doesn't have this issue, it's from `subprocess.Popen(cat(s.path), stdout=f)`. A little testing implies `seqkit` handles unnecessary trailing newlines without any issue, so perhaps we can just add an extra new line to the temp file after cat-ing each input file?

2025-01-07 22:17 UTC, victorlin commented on tests/functional/merge/cram/merge-sequences.t
> +BASIC USAGE
> Probably not, I just found it surprising and wanted to note it here.

Did you mean to quote my question "Do you think it's important to retain the original order?"?

2025-01-07 22:17 UTC, victorlin commented on tests/functional/merge/cram/merge-sequences.t
> +BASIC USAGE
> perhaps we can just add an extra new line to the temp file after cat-ing each input file

Smart thinking! Added as 3d55c60a97eb51029cde5302ca9a7d4071c3f9dc

2025-01-08 08:52 UTC, tsibley requested changes
Gave this a thorough review-by-inspection.¹ The big takeaway for me is that I think we need to revisit the implementation to avoid reading gobs of data into memory. Happy to talk thru what this looks like in comments here or in a 1:1 or two.

¹ I didn't read thru the new test files nor actually run the code but will do both in a second round of review after other changes are made.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +                subprocess.Popen(cat(s.path), stdout=f)
Am I reading this right that each sequence input will be decompressed and written back to disk? That seems very suboptimal (or even a nonstarter) for large datasets. We should be able to do the sequence merging without duplicating the uncompressed data to disk.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +        sequences = list(get_sequences(args.sequences))
_minor_

This `list()` is necessary only incidentally because it's more convenient to implement `get_sequences()` as a generator. Consider making `get_sequences()` return a list so its caller (i.e. right here) doesn't have to care about its internals, even if it uses a generator internally.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +            yield NamedSequenceFile(name, path)
As an example of how to not let the internals of this function leak thru to its return type, consider:

```suggestion
    def sequence_files():
        for name, path in sequences:
            if name == "":
                yield UnnamedSequenceFile(path)
            else:
                yield NamedSequenceFile(name, path)

    return list(sequence_files())
```

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +            """)) from e
Reiterating: I don't think this should be considered invalid.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +        ids = [seq.id for seq in read_sequences(s.path)]
Reading even just the ids into memory is a red flag to me. That's gonna hurt on some datasets, or even be a total nonstarter. The ids should be streamed into SQLite.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +                """))
This duplicate detection can be done without needing the whole list in memory at once (either in Python before load or even just directly in SQLite _after_ load).

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +        db.run(f"insert into {sqlite_quote_id(s.table_name)} ({sqlite_quote_id(SEQUENCE_ID_COLUMN)}) values {values};")
This is gonna run into command-line length limits on real sequence files very quickly and break when it does. Ids need to be streamed into to SQLite.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +                print_info(f"WARNING: Sequence file {x.path!r} is unnamed. Skipping validation with metadata.")
I think one warning would be sufficient (i.e. with all the paths listed), rather than one warning per path.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +        if unnamed_sequences := [s for s in sequences if isinstance(s, UnnamedSequenceFile)]:
The class type testing seems like an awkward way to accomplish this vs. having a single class and testing if `s.name` is truthy or not. e.g.

```python
class Sequences:
    name: str
    table_name: str

    def __init__(self, name: str, path: str):
        self.name = name or ""
        self.path = path
        self.table_name = f"sequences_{self.name or self.path}"
```

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +        if sequences_missing_metadata := sorted(set(sequences_names) - set(metadata_names)):
Don't think `sorted()` is necessary here?

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +                  {indented_list([repr(x.path) for x in named_sequences if x.name in sequences_missing_metadata], '                ' + '  ')}
I'd include the bad inputs as `name=path` in the error message (i.e. not just as `path`), which gives the person staring at the error message two ways to figure out what they're supposed to change.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +        if metadata_missing_sequences := sorted(set(metadata_names) - set(sequences_names)):
Ditto re: `sorted()`.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +                Order of inputs differs between named metadata {metadata_names!r} and named sequences {sequences_names!r}.
```suggestion
                Order of inputs differs between named metadata

                    {metadata_names!r}

                and named sequences

                    {sequences_names!r}
```

makes it easier to spot the difference.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +                """))
I think it'd be friendlier if mismatched names were reported all at once/together instead of potentially hitting an error with one set, fixing it, and then hitting the same error but in the other set.

2025-01-08 08:52 UTC, tsibley commented on augur/merge.py
> +                print_info(f"WARNING: Sequence {x!r} in {s.path!r} is missing from {m.path!r}. Outputs may continue to be mismatched.")
I don't think that reading all of these ids into memory (twice) is gonna fly… these set operations can be done directly in the database, returning just the ones needed for the warning (if any).

2025-01-14 01:33 UTC, victorlin reviewed
@tsibley thanks for the thorough review. I've glanced at most comments and they seem to make sense. I'll plan to address more comments tomorrow.

2025-01-14 01:33 UTC, victorlin commented on augur/merge.py
> +        self.table_name = f"sequences_{re.sub(r'[^a-zA-Z0-9]', '_', os.path.basename(self.path))}"
I had thought that basenames would be the easiest to recognize for debugging and didn't think about collisions or generic names. It seems common to have something like `data-source-1/sequences.fasta` and `data-source-2/sequences.fasta`, so makes sense to add the path.

I forgot that `sqlite_quote_id` will take care of bad characters.

Updated:

https://github.com/nextstrain/augur/blob/2be60e931023e0abda3727c154816d7fea62e60a/augur/merge.py#L155

2025-01-14 17:32 UTC, genehack commented on augur/merge.py
> +this should be considered an implementation detail that may change in the
Suggestion: don't hedge, just state.

```suggestion
SeqKit is used behind the scenes to implement the merge, but
this should be considered an implementation detail that may change in the
```

2025-01-14 17:33 UTC, genehack commented on augur/merge.py
> +environment variable to path of the desired seqkit executable.
nitnitnit

```suggestion
future.  The CLI program seqkit must be available.  If it's not in $PATH (or
you want to use a version different from what's in $PATH), set the SEQKIT
environment variable to the full path of the desired seqkit executable.
```

2025-01-14 17:45 UTC, tsibley commented on augur/merge.py
> +environment variable to path of the desired seqkit executable.
Victor's just following language I introduced; see the description of `SQLITE` in the same `--help` output.

The phrasing "on PATH" is fairly conventional. First, the environment variable name is just `PATH` not `$PATH` and second, the program isn't _in_ `PATH` itself, it's in one of the directories in `PATH`. This is conventionally described as being "on PATH".

2025-01-14 17:46 UTC, genehack commented on augur/merge.py
> +        if sequences_missing_metadata := sorted(set(sequences_names) - set(metadata_names)):
> Don't think `sorted()` is necessary here?

maybe makes the resulting error message nicer?

2025-01-15 17:59 UTC, tsibley commented on augur/merge.py
> +environment variable to path of the desired seqkit executable.
Public code on GitHub is not definitive, but "on PATH" is [widely used](https://github.com/search?q=%2F%28%3F-i%29%28on+PATH%7Con+your+PATH%7Con+the+PATH%29%2F&type=code) to describe a binary's location. The "in PATH" phrasing is also [widely used](https://github.com/search?q=%2F%28%3F-i%29%28in+PATH%7Cin+your+PATH%7Cin+the+PATH%29%2F&type=code), but much of that usage is referring to directories appearing in PATH not just binaries found in those directories.

We can totally use "in PATH" if you want, we should just be consistent.

2025-01-15 18:18 UTC, genehack commented on augur/merge.py
> +environment variable to path of the desired seqkit executable.
I'm fine with "on PATH" if that's the house style, no worries.

2025-01-23 22:37 UTC, victorlin commented
@genehack and @tsibley thanks for taking the time to review this PR. Closing per https://github.com/nextstrain/augur/issues/1579#issuecomment-2611119721, but doing the work here and reading through comments gave me a better understanding of how to work with SQLite in this codebase, which should be useful for future work even if this is not merged.

I've pushed more work in progress as efc48814c287cfcd3bb38ebb37e9fc114eba6da0 in case we ever want to revisit this approach.

2025-01-23 22:37 UTC, closed without merging