merge: Support `--sequences` + `--output-sequences`
nextstrain/augur pull request #1631
Opened 2024-09-16 18:44 UTC by victorlin

## Description of proposed changes

Initial prototype for sequence support in `augur merge` where metadata and sequence merging cannot happen in the same call.

## Related issue(s)

Closes #1579

## Checklist

- [ ] Address FIXMEs
- [ ] Add seqkit as an external dependency (c099e16755c59e8f793ba9eab66ffd080ceb0937)
- [ ] Automated checks pass
- [ ] [Check][1] if you need to add a changelog message
- [ ] [Check][2] if you need to add tests
- [ ] [Check][3] if you need to update docs

[1]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#updating-the-changelog
[2]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#testing
[3]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#when-to-update

2024-10-02 23:53 UTC, victorlin commented
Closing – [the latest plan](https://github.com/nextstrain/augur/issues/1579#issuecomment-2375350108) is to support at least some form of optional cross-checking.

2025-01-23 22:40 UTC, victorlin commented
Re-opening per https://github.com/nextstrain/augur/issues/1579#issuecomment-2611119721. I'll incorporate some newer developments from #1601 before opening for review.

2025-03-21 20:35 UTC, tsibley requested changes
Reviewed by inspection. I didn't look at the tests, though.

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +            with NamedTemporaryFile() as dup_num_file:
Perhaps

```suggestion
            with NamedTemporaryFile("w+", encoding = "utf-8") as dup_num_file:
```

to make properties clearer from the start? and then the `.decode()` after `.read()` below is also not necessary.

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +        done) |
_non-blocking_

This pays Augur startup cost N times, and is also more to digest code-wise. I'd be inclined to make `augur read-file` able to take more than one file and put the loop there in Python.

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +        (for f in {" ".join(shquote(s) for s in reversed(args.sequences))}; do
_non-blocking_

It can be nicely more compact to use `map()` to avoid the list comprehension for simple flows like this, e.g.

```python
" ".join(map(shquote, reversed(args.sequences)))
```

But mostly a preference thing.

(and ditto for `duplicates` above)

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +        # child process with one return code.
_non-blocking_

It's still possible (e.g. with [`PIPESTATUS`](https://www.gnu.org/software/bash/manual/bash.html#index-PIPESTATUS)), but more difficult. May not be worth it.

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +        # FIXME: also clean up metadata merge files, and vice versa?
clean them up under what conditions?

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +            os.remove(args.output_sequences)
Hmm. `-` is not the only way to spell stdout. For example, I might use `--output-sequences /dev/stdout`.

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +    return process.wait()
I don't believe it is safe from deadlock since (when `print_stdout`) all of stdout is read before all of stderr. For example, if the stderr buffer fills up and writers to it block before stdout hits EOF, then I believe we'll block on reading stdout.

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +        for line in iter(process.stdout.readline, ''):
Why not

```suggestion
        for line in process.stdout:
```

Is there something about the `iter()` approach above that I'm missing? 

(and ditto for stderr below)

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +            print_info(line.rstrip())
Why are we bothering with this? It makes the code more complicated, and I'm not sure of what we're gaining?

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +            In order to use `augur merge`, the SeqKit CLI must be installed
_non-blocking_

I don't think there's anything but a CLI for SeqKit?

```suggestion
            In order to use `augur merge`, SeqKit must be installed
```

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +    if not seqkit:
This `not` wants to be on the unquoted value since `shquote("") == "''"`.

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +
_non-blocking_

This sort of function is the perfect candidate for doctests, IMO, so they stay close to the code.

2025-03-21 20:35 UTC, tsibley commented on augur/merge.py
> +        yield line[line.rfind(", ")+2:]
_non-blocking_

I guess we're safe-in-practice from `rfind()`'s return value of `-1` on failure since we expect this to only see lines with at least one `, ` in them.

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +        raise AugurError("--output-sequences requires --sequences.")
Updated to handle all 4 possibilities:

https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/merge.py#L132-L139

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +        raise AugurError("Either --output-metadata or --sequences must be specified.")
Using the 2nd suggestion:

https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/merge.py#L129-L130

I don't think there is an existing convention. The only place that might have it is `augur filter`, and it doesn't because `--metadata` is required.

Also, I removed the 2nd check since the outputs are validated to be paired with inputs which are required.

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +        raise AugurError("Either --output-metadata or --sequences must be specified.")
This line has been dropped with reasoning in https://github.com/nextstrain/augur/pull/1631#discussion_r2023619347

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +            with NamedTemporaryFile() as dup_num_file:
Done:

https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/merge.py#L390

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +            print_info(line.rstrip())
Fair point. I thought it would be good to mark SeqKit's outputs more clearly. I now realize that there is already a [`run_shell_command`](https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/io/shell_command_runner.py#L14) helper function in this codebase, so I've made the switch to that which will mark SeqKit's outputs clearly when there is an error. It needs some tweaking to work nicely for the use cases in this PR, but I think it's better than the `run_command` function that I originally had here.

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +    return process.wait()
Thanks for that example. This is no longer applicable with the switch to `run_shell_command` in https://github.com/nextstrain/augur/pull/1631#discussion_r2008282952

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +        for line in iter(process.stdout.readline, ''):
I think I ended up with the `iter()` approach in an attempt to avoid deadlock issues, but not sure if it actually helped.

This is no longer applicable with the switch to `run_shell_command` in https://github.com/nextstrain/augur/pull/1631#discussion_r2008282952

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +                    raise AugurError(f"Validation failed for {s!r}.")
I've switched to `run_shell_command` in https://github.com/nextstrain/augur/pull/1631#discussion_r2008282952, which allows for better error handling:

https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/merge.py#L396-L399

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +            os.remove(args.output_sequences)
Changed the condition to check for file existence rather than values of `args.output_sequences` that represent stdout or any non-file destination.

https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/merge.py#L429-L434

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +        # FIXME: also clean up metadata merge files, and vice versa?
If both metadata and sequence merging are requested, and sequence merge fails, we'll clean up any partial sequence merge outputs. Should metadata merge outputs be cleaned up as well? Based on the current sequential order of metadata merge followed by sequence merge, which is somewhat arbitrary, metadata outputs would be complete upon sequence merge failure, but maybe they should be removed along with the partial sequence merge outputs.

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +            In order to use `augur merge`, the SeqKit CLI must be installed
Fixed:

https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/merge.py#L601

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +
Doctests added:

https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/merge.py#L631-L649

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +    if not seqkit:
Fixed:

https://github.com/nextstrain/augur/blob/e34a62bdc43a1e12cd8b58277f750a27bb2e20e7/augur/merge.py#L597-L604

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +        # child process with one return code.
No longer applicable with the switch to `run_shell_command` in https://github.com/nextstrain/augur/pull/1631#discussion_r2008282952. Good to know though.

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +        done) |
Good idea, will look into this.

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +                if duplicates := list(parse_seqkit_dup_num_file(dup_num_file.read().decode().strip())):
Good point, I'll look into parsing in a streaming fashion.

2025-04-01 20:40 UTC, victorlin commented on augur/merge.py
> +        (for f in {" ".join(shquote(s) for s in reversed(args.sequences))}; do
The list comprehension is slightly more readable to me, but I see `map` is used elsewhere in this file so I'll switch to that.

2025-05-28 17:28 UTC, tsibley commented on augur/merge.py
> +        yield line[line.rfind(", ")+2:]
I noted the addition of an `if ", " in line:` condition in repush. :+1:

2025-05-28 17:33 UTC, tsibley commented
I realize this is still marked as a draft, but I checked in on it by reviewing the re-push and resolving comment threads as appropriate. Looking good! There are still a few unresolved things left to do.

2025-05-28 18:11 UTC, genehack commented on augur/merge.py
> +        # FIXME: also clean up metadata merge files, and vice versa?
+1 for "leave the metadata outputs but be real loud about sequence failure meaning maybe they're wrong", if that's an option that's not too onerous to implement…

2025-06-03 19:24 UTC, victorlin commented on augur/merge.py
> +                if duplicates := list(parse_seqkit_dup_num_file(dup_num_file.read().decode().strip())):
Updated `parse_seqkit_dup_num_file` to parse in a streaming fashion and used `indented_list` to display the duplicates:

https://github.com/nextstrain/augur/blob/1979c61036850e5de021908797b7f15be06267d0/augur/merge.py#L434-L441

2025-06-03 19:24 UTC, victorlin commented on augur/merge.py
> +            os.remove(args.output_sequences)
Thanks for catching, done:

https://github.com/nextstrain/augur/blob/1979c61036850e5de021908797b7f15be06267d0/augur/merge.py#L411-L413

2025-06-03 19:24 UTC, victorlin commented on augur/merge.py
> +        # FIXME: also clean up metadata merge files, and vice versa?
Added the error handling at the top level:

https://github.com/nextstrain/augur/blob/1979c61036850e5de021908797b7f15be06267d0/augur/merge.py#L151-L159

The output looks like this:

https://github.com/nextstrain/augur/blob/1979c61036850e5de021908797b7f15be06267d0/tests/functional/merge/cram/merge-sequences-errors.t#L24-L36

2025-06-03 19:25 UTC, victorlin commented on augur/merge.py
> +        done) |
Created a separate PR for this: #1815

Using it here:

https://github.com/nextstrain/augur/blob/1979c61036850e5de021908797b7f15be06267d0/augur/merge.py#L399-L403

2025-06-05 18:06 UTC, victorlin commented
Merging as [noted](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1749083684361319?thread_ts=1748984009.610609&cid=C01LCTT7JNN) on Slack.

2025-06-05 18:07 UTC, merged

2025-06-23 18:14 UTC, victorlin commented on augur/merge.py
> +                if duplicates := list(parse_seqkit_dup_num_file(dup_num_file.read().decode().strip())):
It's not ideal, but 80cbb0d36b1b9b67bc0ffbb5ed6b02848232f96d changes this function to store a potentially large set of ids in memory.