Support Python 3.12, test 3.12 and 3.13 in CI
nextstrain/augur pull request #1678
Opened 2024-11-14 12:10 UTC by corneliusroemer

## Description of proposed changes

## Related issue(s)

## Checklist

- [ ] Automated checks pass
- [ ] [Check][1] if you need to add a changelog message
- [ ] [Check][2] if you need to add tests
- [ ] [Check][3] if you need to update docs

[1]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#updating-the-changelog
[2]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#testing
[3]: https://github.com/nextstrain/augur/blob/-/docs/contribute/DEV_DOCS.md#when-to-update

2024-11-14 18:11 UTC, genehack approved these changes

2024-11-14 18:12 UTC, victorlin requested changes

2024-11-14 18:12 UTC, victorlin commented on .github/workflows/ci.yaml
> +          - '1.82' # first to support Python 3.12
```suggestion
          - '1.80' # first to support Python 3.10 and 3.11
          - '1.82' # first to support Python 3.12
```

The new version should be added, not replaced. Then some combinations of biopython+python versions might need to be excluded. See the previous usage:

https://github.com/nextstrain/augur/blob/509c193ac5e8dd008011e927520f138ee019af52/.github/workflows/ci.yaml#L27-L42

2024-11-15 03:20 UTC, victorlin approved these changes

2024-11-16 12:19 UTC, merged