filter: Rewrite priority queue logic with pandas functions
nextstrain/augur pull request #809
Opened 2021-12-10 10:04 UTC by victorlin

### Description of proposed changes

- remove `class PriorityQueue`
- use `prioritized_metadata` DataFrame in place of `queues_per_group`
    - this also removes the need for a second call to `get_groups_for_subsampling`
- repurpose `create_queues_per_group` to `create_sizes_per_group`
- other logical refactoring:
    - use global dummy group key and value
        - key is `list`: pd.DataFrame.groupby does not take a tuple as grouping key, also our `--group-by` is stored as list already.
        - value is `tuple`: `get_groups_for_subsampling` returns group values in this form.
    - use `records_per_group` for `_dummy`
        - replace conditional logic of `records_per_group is not None` with `group_by`
        - add TODO to rewrite logic for `records_per_group` with pandas functions
    - move date-expanding logic from `get_groups_for_subsampling` to a separate function: https://github.com/nextstrain/augur/commit/1b106d5e25f96170ee8c1ec8c3a09b0057e18a21
    - store unique group values globally: https://github.com/nextstrain/augur/commit/4e3e155ab1dfd8d686917787e0e52d9e2112efa2, https://github.com/nextstrain/augur/pull/809/commits/6296d8eefd592902a5150f40156f2693dcb8ebc2
### Related issue(s)  

- #789

### Testing

- Added functional tests for groupby

2021-12-17 22:16 UTC, huddlej requested changes
Thank you for this huge effort, @victorlin! This PR represents a lot of work both in managing complexity of the filter module and coming up with a solution to use vectorized operations with pandas. 

Before I get to the specific implementation details, here are some performance results for the code in this PR vs. Augur 13.1.0. First, I got a random sample of 10 strains from Nebraska with the full GenBank (“open”) metadata. This command took slightly longer to run with the current implementation.

```
# Get 10 random sequences with "dummy" group.
# Ran in 3.5 min instead of 2 min pre-PR.
augur filter \
  --metadata metadata.tsv.gz \
  --query "division == 'Nebraska'" \
  --subsample-max-sequences 10 \
  --output-metadata nebraska_random_metadata.tsv \
  --output-strains nebraska_random_strains.txt
```

Next, I tried getting 10 random sequences per month. This command ran for 3 minutes before crashing.

```
# Get 10 random sequences by month.
# Ran in 3 min before crashing.
augur filter \
  --metadata metadata.tsv.gz \
  --query "division == 'Nebraska'" \
  --subsample-max-sequences 10 \
  --group-by month \
  --output-metadata nebraska_random_metadata.tsv \
  --output-strains nebraska_random_strains.txt
```

The exception from the command above was:
```python
Traceback (most recent call last):
  File "/Users/jlhudd/miniconda3/envs/nextstrain/bin/augur", line 33, in <module>
    sys.exit(load_entry_point('nextstrain-augur', 'console_scripts', 'augur')())
  File "/Users/jlhudd/projects/nextstrain/augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/Users/jlhudd/projects/nextstrain/augur/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/Users/jlhudd/projects/nextstrain/augur/augur/filter.py", line 1479, in run
    metadata_copy.groupby(group_by, sort=False)['priority']
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 948, in wrapper
    return self._python_apply_general(curried, self._obj_with_exclusions)
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1311, in _python_apply_general
    return self._wrap_applied_output(
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 472, in _wrap_applied_output
    return self._concat_objects(keys, values, not_indexed_same=not_indexed_same)
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1044, in _concat_objects
    result = concat(
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 371, in __init__
    keys = Index(clean_keys, name=name)
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 489, in __new__
    return MultiIndex.from_tuples(
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 202, in new_meth
    return meth(self_or_cls, *args, **kwargs)
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 560, in from_tuples
    return cls.from_arrays(arrays, sortorder=sortorder, names=names)
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 487, in from_arrays
    return cls(
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 331, in __new__
    result._set_names(names)
  File "/Users/jlhudd/miniconda3/envs/nextstrain/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 1423, in _set_names
    raise ValueError("Names should be list-like for a MultiIndex")
ValueError: Names should be list-like for a MultiIndex
```

The error specifically occurs with this call:

```python
metadata_copy.groupby(group_by, sort=False)["priority"].nlargest(int_group_size, keep='last')
```

where `group_by` is `month` and `int_group_size` is 4. It turns out that pandas (1.3.4) interprets the (year, month) tuple in the `month` column as a MultiIndex and expects the values to be in a list. Commit 897d00e46d72dce874818f44303d3c5aed85bcc4 adds a functional test that fails with this specific error.

This feels like a pandas edge case, but it also highlights a strange implementation choice in our code. In the original augur filter, we grouped by storing records in dictionaries by group key. At the time, it seemed to make sense to store month values as year/month tuples, so avoid meaninglessly sampling across years when grouping by month alone. This choice no longer makes much sense now that we use pandas DataFrames where year and month have their own columns and grouping on these is simple. If we want to implicitly group by year and month when the user asks for month, I think that logic should live closer to the highest level of the filter module and not live in the filter internal functions. Commit 966da1d07e2e7809fe34e8e709680fcdc609176a makes this change and commit eea96fb4d85e1dd9554ee788591c848577e97690 updates unit tests and doctests to reflect this change.

With this fix in place, I re-ran the filter for 10 random Nebraska sequences grouped by month. It ran in 4 minutes, the same amount of time required with Augur 13.1.0.

Next, I ran Trevor’s more complex filter command on the full sanitized GISAID data as shown below. This took 11 minutes with this PR and 17 minutes with Augur 13.1.0.

```
# Run Trevor's filter command on full sanitized GISAID data.
# This took 24 minutes with Augur 13.0.3.
# It took 17 minutes with Augur 13.1.0.
# It took 11 minutes with the new groupby priorities logic.
time augur filter \
 --metadata sanitized_metadata_gisaid.tsv.xz \
 --include defaults/include.txt \
 --exclude defaults/exclude.txt \
 --min-date 2021-07-28 \
 --exclude-where 'region!=Europe' \
 --group-by country year month \
 --subsample-max-sequences 10 \
 --probabilistic-sampling \
 --output-strains sample-europe_late.txt
```

For reference, here are some equivalent commands with tsv-utils for the two Nebraska examples above (it’s less obvious how to completely map Trevor’s filter command to tsv-utils, though it seems possible):

```
# Get all Nebraska metadata.
# Runs in 4 seconds.
time gzip -c -d metadata.tsv.gz | tsv-filter -H --str-eq division:Nebraska > all_nebraska_metadata.tsv

# Get 10 random metadata records from Nebraska.
# Runs in 3 seconds.
gzip -c -d metadata.tsv.gz | tsv-filter -H --str-eq division:Nebraska | tsv-sample -H --n 10 > random_nebraska_metadata.tsv
```

Overall, there seems to be a slight performance loss to the new implementation for smaller queries and a performance increase for larger queries. This outcome makes sense to me for a couple of reasons:

1. We now make two passes through the metadata for all group-by queries whereas the 13.1.0 implementation only makes a second pass when the number of sequences per group is unknown (`--subsample-max-sequences` and `--group-by` are defined). I would expect the code in this PR to be slightly slower for the use case where users provide a known number of sequences per group. 
2. We now consider the number of sequences per group as unknown when the user provides `--subsample-max-sequences` and no `--group-by` values whereas the 13.1.0 knows the resulting “dummy” group needs as many sequences per group as total requested sequences. I suspect this is why the first Nebraska filter above is slightly slower now than in 13.1.0.

On the other hand, we are not making two calls to `g [...]

2021-12-30 20:05 UTC, victorlin commented
Converting to draft due outstanding issues and and discussion of an alternative option.

2025-01-13 20:20 UTC, genehack commented
@victorlin is this PR still relevant?

2025-01-13 22:48 UTC, victorlin commented
The idea of [speeding up augur filter](https://github.com/nextstrain/augur/issues/1575) is still relevant, which we now have an issue for. This PR an attempt under the category of [without replacing Pandas](https://github.com/nextstrain/augur/issues/1573). I think any speedup in priority queue logic is better suited for an attempt under the category of [replacing Pandas](https://github.com/nextstrain/augur/issues/1574).

2025-01-13 22:48 UTC, closed without merging