filter: Update functional test coverage
nextstrain/augur pull request #922
Opened 2022-05-13 21:10 UTC by victorlin

### Description of proposed changes

Improves coverage of existing functional tests, motivated by work in #854. See individual commits.

### Related issue(s)

_N/A_

### Testing

See tests.

2022-05-23 21:41 UTC, huddlej requested changes
I just realized from the modified metadata and sequence index that I never explicitly documented my logic behind the data for these functional tests.

My thinking was that the sequences and metadata and their downstream processed files in `tests/functional/filter/` should be logically consistent such that you could always regenerate the downstream files from these starting points. For example, the sequence index in that directory is the output of `augur index --sequences sequences.fasta --output sequence_index.tsv`. As we add test cases that requite new data to represent the test (e.g., sequences with non-nucleotides), we can add those data to the FASTA and metadata files, as needed.

In this PR, I'm worried that modifying the sequence index directly and copying the metadata TSV to CSV will decouple the original source data from the test outputs. In the current framework (that I hadn't documented anywhere until this comment), I'd opt to add a new sequence entry to `sequences.fasta` with an invalid nucleotide character and a corresponding entry to `metadata.tsv`. I would first look for a real record from the full Zika dataset, in case one exists that would be a realistic example. Otherwise, I would copy a record from the existing data and give it a new strain name. (I don't see any invalid nucleotides in [the example data](https://github.com/nextstrain/zika/blob/main/example_data/sequences.fasta), so we'd need to go to fauna or full data on S3).

Regarding the metadata CSV input, this feels like more of a test of `io.read_metadata` than `augur filter`. Is there CSV-specific filter logic in the sqlite branch that needs testing there? Or can we drop the metadata CSV test here?

Maybe we can have a separate conversation about how to manage data in functional tests? Even if the answer is to just document the plan I had in my head, that would be better than nothing... :)

2022-05-25 22:52 UTC, victorlin commented
@huddlej

> In this PR, I'm worried that modifying the sequence index directly and copying the metadata TSV to CSV will decouple the original source data from the test outputs.

Valid, I made these changes naively with the single goal of increasing code coverage. I hadn't thought about decoupling.

> Regarding the metadata CSV input, this feels like more of a test of `io.read_metadata` than `augur filter`. Is there CSV-specific filter logic in the sqlite branch that needs testing there? Or can we drop the metadata CSV test here?

I agree that this is more a test of `io.read_metadata` and should be moved. Mainly since we support CSV input, I wanted to test that this functionality also makes its way to the sqlite engine. It's currently not using `io.read_metadata`, which is another problem I'll need to solve first. But overall, more coverage in `filter` and supporting modules like `io` makes me more confident that the rewrite has functional parity with the existing pandas engine.

> Maybe we can have a separate conversation about how to manage data in functional tests? Even if the answer is to just document the plan I had in my head, that would be better than nothing... :)

Good idea, maybe a README alongside data files will suffice. I'll start a PR based on your 2nd paragraph above.

2022-05-26 23:52 UTC, tsibley commented
> My thinking was that the sequences and metadata and their downstream processed files in `tests/functional/filter/` should be logically consistent such that you could always regenerate the downstream files from these starting points.

+1 for maintaining this property, which is adjacent to snapshot/"known good" testing.

2025-01-13 20:27 UTC, genehack commented
@victorlin can this old PR be closed out?

2025-01-13 22:09 UTC, victorlin commented
Yes, closing. We may still want to add a test somewhere that `--non-nucleotide` actually works as expected, but that should be done differently than proposed in this PR.

As for CSV metadata, I don't think this is something we need to strictly support. We could however update the help text for `augur filter --metadata` to state that only TSV files are officially supported.

2025-01-13 22:09 UTC, closed without merging